name: models
description: "Models for the Multichoice app"
publish_to: "none"

version: 0.0.1

environment:
  sdk: ">=3.10.8 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  auto_mappr: ^2.3.0
  auto_mappr_annotation: ^2.1.0
  clock: ^1.1.1
  cloud_firestore: ^6.1.2
  copy_with_extension: ^9.0.0
  flutter:
    sdk: flutter
  isar_community: ^3.3.0
  isar_community_flutter_libs: ^3.3.0
  json_annotation: ^4.9.0
  path_provider: ^2.1.2
  path_provider_platform_interface: ^2.1.2
  uuid: ^4.3.3

dev_dependencies:
  build_runner: ^2.4.8
  copy_with_extension_gen: ^9.0.0
  flutter_test:
    sdk: flutter
  isar_community_generator: ^3.3.0
  json_serializable: ^6.7.1
  very_good_analysis: ^10.0.0
