name: models
description: "Models for the Multichoice app"
publish_to: "none"

version: 0.0.1

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  auto_mappr: ^2.3.0
  auto_mappr_annotation: ^2.1.0
  clock: ^1.1.1
  cloud_firestore: ^5.6.8
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1
  isar_community: ^3.2.0
  isar_community_flutter_libs: ^3.2.0
  json_annotation: ^4.8.1
  path_provider: ^2.1.2
  path_provider_platform_interface: ^2.1.2
  uuid: ^4.3.3

dev_dependencies:
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  isar_community_generator: ^3.2.0
  json_serializable: ^6.7.1
  very_good_analysis: ^7.0.0

global_options:
  freezed:freezed:
    runs_before:
      - isar_community_generator:isar_community_generator
