name: theme
description: "The theme package used in the Multichoice repo."
version: 0.0.1
publish_to: "none"

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  build_runner: ^2.4.15
  flutter:
    sdk: flutter
  theme_tailor_annotation: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  theme_tailor: ^3.0.1
  very_good_analysis: ^7.0.0
