name: multichoice
description: "The monorepo for the Multichoice project"
publish_to: "none"

version: 0.1.0+1

environment:
  sdk: ">=3.10.8 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  melos: ^6.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.0.0
