name: ui_kit
description: A collection of reusable UI widgets for the Multichoice app.
version: 0.0.1
homepage: https://github.com/yourusername/multichoice

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  build_runner: ^2.4.15
  flutter:
    sdk: flutter
  gap: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
