name: application
description: "Application layer for the app."
version: 0.0.1
homepage:
publish_to: none

dependency_overrides:
  domain:
    path: ../domain

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  domain: ^0.0.1
  build_runner: ^2.4.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

