name: core
description: "The core package used in the Multichoice repo"
version: 0.0.1
publish_to: "none"

environment:
  sdk: ">=3.10.8 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  bloc: ^9.0.0
  clock: ^1.1.1
  cloud_firestore: ^6.1.2
  dartz: ^0.10.1
  copy_with_extension: ^9.0.0
  file_picker: ^10.1.9
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  freezed_annotation: ^3.1.0
  get_it: ^8.0.3
  injectable: ^2.3.2
  isar_community: ^3.3.0
  isar_community_flutter_libs: ^3.3.0
  json_annotation: ^4.9.0
  models: ^0.0.1
  package_info_plus: ^9.0.0
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2
  showcaseview: ^5.0.1
  uuid: ^4.3.3
  version: ^3.0.2

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.4.8
  copy_with_extension_gen: ^9.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.2.3
  injectable_generator: ^2.4.1
  json_serializable: ^6.7.1
  mockito: ^5.4.4
  very_good_analysis: ^10.0.0
  path_provider_platform_interface: ^2.1.2

flutter:
  assets:
    - assets/test_data/

global_options:
  freezed:freezed:
    runs_before:
      - isar_community_generator:isar_community_generator
