name: domain
description: "Domain layer for the app."
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  build_runner: ^2.4.15
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  freezed: ^2.4.7
  json_serializable: ^6.7.1

flutter:
